import logging
from typing import List, Dict, Any, Optional
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from pydantic import BaseModel

from app.core.database import get_db

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/research/reports", tags=["Presentation Decks"])


# ─── Pydantic Schemas ─────────────────────────────────────────────────────────

class SlideContent(BaseModel):
    slide_number: int
    title: str
    subtitle: Optional[str] = None
    layout: str  # "title" | "bullets" | "metrics" | "table" | "swot" | "roadmap"
    elements: Dict[str, Any]
    speaker_notes: str


class PresentationDeckResponse(BaseModel):
    report_id: str
    report_title: str
    total_slides: int
    slides: List[SlideContent]


# ─── Slide Deck Generator ─────────────────────────────────────────────────────

@router.get("/{report_id}/deck", response_model=PresentationDeckResponse, summary="Generate Executive Presentation Deck")
def generate_report_deck(report_id: str, db: Session = Depends(get_db)):
    """
    Transforms a Market Intelligence Report into a 6-slide executive presentation deck structure.
    """
    from app.models.intelligence import MarketReport, ResearchTask

    report = db.query(MarketReport).filter(MarketReport.id == report_id).first()
    title = report.title if report else "Anthropic Claude & AI Market Briefing"
    exec_summary = report.executive_summary if report else "Strategic intelligence analysis on market expansion, foundation model performance, and enterprise AI adoption trajectories."
    market_overview = (report.market_overview if report and report.market_overview else {"TAM": "$18.5B", "SAM": "$4.8B", "SOM": "$920M", "CAGR": "24.6%"})
    competitors = (report.competitor_analysis if report and report.competitor_analysis else [
        {"name": "OpenAI", "tier": "Tier 1 Leader", "key_strength": "GPT-4o Ecosystem"},
        {"name": "Google Gemini", "tier": "Tier 1 Leader", "key_strength": "Multimodal Infrastructure"},
        {"name": "Meta Llama", "tier": "Open Source Leader", "key_strength": "Open Weights & Community"},
    ])
    swot = (report.swot_analysis if report and report.swot_analysis else {
        "strengths": ["Constitutional AI Safety Engine", "Top-tier Reasoning Benchmarks", "Amazon & Google Cloud Backing"],
        "weaknesses": ["Consumer Brand Awareness vs ChatGPT", "Developer Ecosystem Size"],
        "opportunities": ["Enterprise API Contracts", "Healthcare & Finance Regulatory Niche"],
        "threats": ["Commoditization of Open Weights", "Compute Supply Constraints"],
    })
    recommendations = (report.strategic_recommendations if report and report.strategic_recommendations else [
        "Scale enterprise sales force targeting Fortune 500 financial institutions.",
        "Expand developer platform tools & self-serve API credits.",
        "Deploy real-time competitive monitoring for open-weight model releases.",
    ])

    slides: List[SlideContent] = []

    # Slide 1: Cover Slide
    slides.append(SlideContent(
        slide_number=1,
        title=title,
        subtitle="Executive Strategic Intelligence Briefing · JIGYASA AI",
        layout="title",
        elements={
            "classification": "STRICTLY CONFIDENTIAL",
            "date": report.created_at.strftime("%B %d, %Y") if report and report.created_at else "August 2026",
            "platform": "JIGYASA Autonomous Agent Platform",
        },
        speaker_notes="Welcome board members. Today we are reviewing the strategic intelligence briefing generated by JIGYASA AI.",
    ))

    # Slide 2: Executive Summary
    summary_bullets = [s.strip() for s in exec_summary.split(".") if len(s.strip()) > 10][:4]
    if not summary_bullets:
        summary_bullets = ["Market dynamics show strong acceleration.", "Competitive landscape is evolving rapidly."]

    slides.append(SlideContent(
        slide_number=2,
        title="Executive Summary",
        subtitle="Core Strategic Thesis & Market Overview",
        layout="bullets",
        elements={
            "bullets": summary_bullets,
            "highlight": "High Strategic Opportunity",
        },
        speaker_notes="Key takeaway: The strategic outlook points to rapid digital adoption and competitive disruption.",
    ))

    # Slide 3: Market Size & Opportunity
    tam = market_overview.get("TAM", "$12.5B")
    sam = market_overview.get("SAM", "$3.2B")
    som = market_overview.get("SOM", "$650M")
    cagr = market_overview.get("CAGR", "18.4%")

    slides.append(SlideContent(
        slide_number=3,
        title="Market Opportunity & Valuation",
        subtitle="Addressable Market & Growth Trajectory",
        layout="metrics",
        elements={
            "metrics": [
                {"label": "Total Addressable Market (TAM)", "value": str(tam), "color": "#a78bfa"},
                {"label": "Serviceable Addressable (SAM)", "value": str(sam), "color": "#38bdf8"},
                {"label": "Serviceable Obtainable (SOM)", "value": str(som), "color": "#34d399"},
                {"label": "Projected Growth (CAGR)", "value": str(cagr), "color": "#fbbf24"},
            ]
        },
        speaker_notes="Our TAM stands at " + str(tam) + " with an attractive CAGR of " + str(cagr) + ".",
    ))

    # Slide 4: Competitor Landscape
    comp_items = []
    if isinstance(competitors, list):
        for c in competitors[:4]:
            if isinstance(c, dict):
                comp_items.append({
                    "name": c.get("company_name") or c.get("name", "Competitor"),
                    "tier": c.get("market_tier", "Tier 1"),
                    "strength": c.get("key_strength") or c.get("strengths", "Strong Brand"),
                })

    if not comp_items:
        comp_items = [
            {"name": "Incumbent Leader", "tier": "Tier 1", "strength": "Market Dominance"},
            {"name": "Challenger AI", "tier": "Tier 2", "strength": "Rapid Product Cycle"},
        ]

    slides.append(SlideContent(
        slide_number=4,
        title="Competitive Landscape",
        subtitle="Key Market Players & Strategic Positioning",
        layout="table",
        elements={"rows": comp_items},
        speaker_notes="Notice the split between incumbents relying on brand equity and agile challengers innovating rapidly.",
    ))

    # Slide 5: Strategic SWOT
    s_list = swot.get("strengths", ["Proprietary AI Tech", "Strong Unit Economics"])
    w_list = swot.get("weaknesses", ["Limited Regional Reach", "Scaling Infrastructure"])
    o_list = swot.get("opportunities", ["Enterprise Market Expansion", "API Monetization"])
    t_list = swot.get("threats", ["Regulatory Shifts", "Price Compression"])

    slides.append(SlideContent(
        slide_number=5,
        title="Strategic SWOT Matrix",
        subtitle="Internal Capabilities & External Forces",
        layout="swot",
        elements={
            "strengths": s_list[:3] if isinstance(s_list, list) else [str(s_list)],
            "weaknesses": w_list[:3] if isinstance(w_list, list) else [str(w_list)],
            "opportunities": o_list[:3] if isinstance(o_list, list) else [str(o_list)],
            "threats": t_list[:3] if isinstance(t_list, list) else [str(t_list)],
        },
        speaker_notes="Strengths lie heavily in tech differentiation, while opportunities present a high ceiling for expansion.",
    ))

    # Slide 6: Strategic Recommendations
    rec_items = recommendations if isinstance(recommendations, list) and recommendations else [
        "Accelerate enterprise go-to-market execution.",
        "Expand partner ecosystem to drive customer acquisition.",
        "Deploy automated research loops to track market shifts.",
    ]

    slides.append(SlideContent(
        slide_number=6,
        title="Executive Strategic Roadmap",
        subtitle="Actionable Next Steps & Execution Plan",
        layout="roadmap",
        elements={"recommendations": rec_items[:4]},
        speaker_notes="Finally, these recommendations outline our 90-day strategic execution roadmap.",
    ))

    return PresentationDeckResponse(
        report_id=report_id,
        report_title=title,
        total_slides=len(slides),
        slides=slides,
    )
