from fastapi import APIRouter, Depends, HTTPException, Query, Response
from sqlalchemy.orm import Session
from typing import List, Optional

from app.core.database import get_db
from app.models.intelligence import ResearchTask, MarketReport, TaskStatus
from app.schemas.intelligence import (
    ResearchRequest,
    TaskStatusResponse,
    MarketReportResponse
)
from app.services.research_service import ResearchService

router = APIRouter(prefix="/research", tags=["Market Research"])


@router.post("/start", response_model=TaskStatusResponse, summary="Start Market Intelligence Task")
def start_research_task(request: ResearchRequest, db: Session = Depends(get_db)):
    """
    Initiates an asynchronous multi-stage market intelligence research task.
    Returns the task ID to track progress and logs.
    """
    task = ResearchService.create_task(db, request)
    ResearchService.execute_task_async(task.id)
    return task


@router.get("/tasks/{task_id}", response_model=TaskStatusResponse, summary="Get Research Task Status")
def get_task_status(task_id: str, db: Session = Depends(get_db)):
    """
    Returns the real-time execution status, progress percentage, and logs for a task.
    """
    task = db.query(ResearchTask).filter(ResearchTask.id == task_id).first()
    if not task:
        raise HTTPException(status_code=404, detail=f"Research task '{task_id}' not found.")
    
    report = db.query(MarketReport).filter(MarketReport.task_id == task_id).first()
    response_data = TaskStatusResponse.from_orm(task)
    if report:
        response_data.report_id = report.id
    return response_data


@router.get("/reports/{report_id}", response_model=MarketReportResponse, summary="Get Full Market Report")
def get_market_report(report_id: str, db: Session = Depends(get_db)):
    """
    Retrieves the complete structured market intelligence dossier.
    """
    report = db.query(MarketReport).filter(MarketReport.id == report_id).first()
    if not report:
        raise HTTPException(status_code=404, detail=f"Market report '{report_id}' not found.")
    return report


@router.get("/reports/{report_id}/export", summary="Export Market Report as Markdown")
def export_market_report(report_id: str, format: str = Query("markdown"), db: Session = Depends(get_db)):
    """
    Exports the synthesized market intelligence dossier as a presentation-grade Markdown document.
    """
    report = db.query(MarketReport).filter(MarketReport.id == report_id).first()
    if not report:
        raise HTTPException(status_code=404, detail=f"Market report '{report_id}' not found.")
    
    overview = report.market_overview or {}
    swot = report.swot_analysis or {}
    comps = report.competitor_analysis or []
    recs = report.strategic_recommendations or []
    risks = report.risk_matrix or []
    citations = report.raw_evidence or []

    md = []
    md.append(f"# {report.title}")
    md.append(f"*Generated by Alkame AI Market Intelligence Platform on {report.created_at.strftime('%Y-%m-%d %H:%M:%S')} UTC*\n")
    
    md.append("## 1. Executive Summary")
    md.append(f"{report.executive_summary}\n")

    md.append("## 2. Market Sizing & Macro Industry Dynamics")
    md.append(f"- **TAM (Total Addressable Market):** {overview.get('tam', 'N/A')}")
    md.append(f"- **SAM (Serviceable Addressable Market):** {overview.get('sam', 'N/A')}")
    md.append(f"- **SOM (Serviceable Obtainable Market):** {overview.get('som', 'N/A')}")
    md.append(f"- **Estimated CAGR:** {overview.get('cagr', 'N/A')}\n")
    
    if overview.get("key_trends"):
        md.append("### Key Industry Trends & Catalysts")
        for t in overview.get("key_trends", []):
            md.append(f"- {t}")
        md.append("")

    md.append("## 3. Competitor Intelligence & Battlecard Benchmarks")
    for c in comps:
        md.append(f"### {c.get('name')} ({c.get('market_position')})")
        md.append(f"- **Estimated Market Share:** {c.get('estimated_market_share', 'N/A')}")
        md.append(f"- **Pricing Strategy:** {c.get('pricing_strategy')}")
        md.append(f"- **Target Customer Segment:** {c.get('target_segment')}")
        md.append(f"- **Core Differentiation / Moat:** {c.get('differentiation_factor')}")
        md.append(f"- **Key Strengths:** {', '.join(c.get('key_strengths', []))}")
        md.append(f"- **Key Vulnerabilities:** {', '.join(c.get('key_weaknesses', []))}\n")

    md.append("## 4. SWOT Analysis Matrix")
    md.append("### Strengths")
    for s in swot.get("strengths", []):
        md.append(f"- {s}")
    md.append("\n### Weaknesses")
    for w in swot.get("weaknesses", []):
        md.append(f"- {w}")
    md.append("\n### Opportunities")
    for o in swot.get("opportunities", []):
        md.append(f"- {o}")
    md.append("\n### Threats")
    for t in swot.get("threats", []):
        md.append(f"- {t}")
    md.append("")

    md.append("## 5. Strategic Action Roadmap & Impact")
    for r in recs:
        md.append(f"### [{r.get('priority')} Priority | {r.get('timeframe')}] {r.get('title')}")
        md.append(f"{r.get('description')}")
        md.append(f"**Expected Business Impact:** {r.get('expected_impact')}\n")

    md.append("## 6. Risk Assessment Matrix")
    for rk in risks:
        md.append(f"- **{rk.get('risk_title')}** (Severity: {rk.get('severity')}, Likelihood: {rk.get('likelihood')}): {rk.get('mitigation_strategy')}")
    md.append("")

    if citations:
        md.append("## 7. Verified Sourced Evidence & Citations")
        for ct in citations:
            md.append(f"- [{ct.get('title', ct.get('source'))}]({ct.get('url')}): *\"{ct.get('snippet', '')}\"*")
        md.append("")

    markdown_text = "\n".join(md)
    return Response(
        content=markdown_text,
        media_type="text/markdown",
        headers={"Content-Disposition": f"attachment; filename=market_dossier_{report_id}.md"}
    )


@router.get("/reports", response_model=List[MarketReportResponse], summary="List Market Reports")
def list_market_reports(
    limit: int = Query(20, ge=1, le=100),
    project_id: Optional[str] = None,
    db: Session = Depends(get_db)
):
    """
    Lists generated market intelligence reports ordered by creation date.
    """
    query = db.query(MarketReport)
    if project_id:
        query = query.filter(MarketReport.project_id == project_id)
    reports = query.order_by(MarketReport.created_at.desc()).limit(limit).all()
    return reports


@router.post("/quick-analyze", response_model=MarketReportResponse, summary="Quick Synchronous Analysis")
def quick_analyze(request: ResearchRequest, db: Session = Depends(get_db)):
    """
    Performs immediate synchronous market intelligence analysis and returns the dossier.
    """
    report = ResearchService.execute_quick_sync(db, request)
    return report
